---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot-aug8-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-aug8-1 
  name: chatbot-aug8-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi